### ISSUE TITLE
Produce some end-of-semester documentation

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/dsg-mhs#11]
This should include information about what you learned, what will future developers need to learn, and other thoughts that will be helpful to a future Hany.

**Comment by Hanyrz** [comment]
Hello Patrick,
I hope the below document helps.
[MHS_Next_Tasks.docx](https://github.com/NEU-DSG/dsg-mhs/files/11238438/MHS_Next_Tasks.docx)
